import type { MetadataRoute } from 'next';

/**
 * What makes this install to a home screen, and D12's whole PWA story — because
 * the other half of that story is what is deliberately absent.
 *
 * **There is no service worker, and that is the decision rather than an
 * omission.** Offline play is meaningless here: a room is other people's taps
 * arriving over a stream, so a cached shell with no API is a card that cannot be
 * called. What a service worker would add instead is the one failure this cannot
 * afford — a stale bundle served to a phone on race day, an hour into a race,
 * with no way to tell the room to hard-refresh. `gate/install.gate.ts` asserts
 * that none is registered, so this stays a decision rather than a comment.
 *
 * Icons are placeholder art (a monogram on `neutral-950`), checked in as real
 * PNGs rather than generated by `next/og` at build: the manifest needs stable
 * 192/512 URLs, and `icon.tsx` + `icon1.tsx` to get two sizes reads worse than
 * four files that say what they are.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'TwinIon Bingo',
    short_name: 'Bingo',
    description: 'Themed multiplayer bingo where the squares are events.',
    start_url: '/',
    display: 'standalone',
    /*
      `neutral-950`: the *default* skin's surface, which is no longer the same
      claim as "the only one". #102 gave the app four skins, two of them light,
      and `layout.tsx`'s `generateViewport()` now varies `themeColor` per skin
      from a cookie. A web manifest cannot: it is one static document for the
      installed app, so it cannot follow a per-request cookie the way a viewport
      tag can.

      So the invariant `layout.tsx` used to record — an installed launch and a
      browser tab tint the same — is retired here on purpose rather than
      quietly: it holds for Pit Wall, which is what a fresh install gets and
      what `docs/SURFACES.md`'s note describes, and it breaks for a player who
      has switched to Confetti or Scorecard and then installs. The splash stays
      dark for them, which is the smaller failure than flashing white on the way
      in for everyone. Making the installed splash follow the skin needs a
      client-side manifest swap, and that belongs to whichever slice mounts the
      button rather than to the token layer.
    */
    background_color: '#0a0a0a',
    theme_color: '#0a0a0a',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
