import type { MetadataRoute } from 'next';

/**
 * What makes this install to a home screen, and D12's whole PWA story — because
 * the other half of that story is what is deliberately absent.
 *
 * **There is no service worker, and that is the decision rather than an
 * omission.** Offline play is meaningless here: a room is other people's taps
 * arriving over a stream, so a cached shell with no API is a card that cannot be
 * called. What a service worker would add instead is the one failure this cannot
 * afford — a stale bundle served to a phone on race day, an hour into a race,
 * with no way to tell the room to hard-refresh. `gate/install.gate.ts` asserts
 * that none is registered, so this stays a decision rather than a comment.
 *
 * Icons are placeholder art (a monogram on `neutral-950`), checked in as real
 * PNGs rather than generated by `next/og` at build: the manifest needs stable
 * 192/512 URLs, and `icon.tsx` + `icon1.tsx` to get two sizes reads worse than
 * four files that say what they are.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'TwinIon Bingo',
    short_name: 'Bingo',
    description: 'Themed multiplayer bingo where the squares are events.',
    start_url: '/',
    display: 'standalone',
    // `neutral-950`, and dark is the only theme this project has — see the note
    // in `docs/SURFACES.md`. So the splash matches the app rather than flashing
    // white on the way in.
    background_color: '#0a0a0a',
    theme_color: '#0a0a0a',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
      {
        src: '/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
